M48
; DRILL file {KiCad (6.0.11)} date Thu Feb  2 14:04:34 2023
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-02-02T14:04:34+00:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.11)
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0472
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0591
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C0.0941
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T4C0.0945
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T5C0.1122
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T6C0.1378
%
G90
G05
T1
X14.29Y-0.8622
X14.29Y-0.9606
X14.4869Y-1.1575
X14.6837Y-0.8622
X14.6837Y-0.9606
T2
X6.9476Y-1.4955
X7.9004Y-1.4955
T3
X1.7355Y-1.0817
X2.3264Y-1.0817
T4
X8.5597Y-1.096
X9.1503Y-1.096
T5
X2.86Y-0.9
X6.36Y-0.9
T6
X8.45Y-2.3659
T0
M30
