M48
; DRILL file {KiCad 7.0.9} date Mon Feb  5 15:13:05 2024
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-02-05T15:13:05+00:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.9
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0472
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.1122
%
G90
G05
T1
X7.5047Y-3.6446
X7.7016Y-3.4478
X7.7016Y-3.8415
X7.8Y-3.4478
X7.8Y-3.8415
T2
X4.1301Y-5.7972
X7.6301Y-5.7972
T0
M30
