M48
; DRILL file {KiCad (6.0.7-rc1-83-g1005f75cdb)} date Wed Aug 17 14:22:40 2022
; FORMAT={2:4/ absolute / inch / suppress leading zeros}
; #@! TF.CreationDate,2022-08-17T14:22:40+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.7-rc1-83-g1005f75cdb)
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH,TZ
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1122
%
G90
G05
T1
X41400Y-58000
X76400Y-58000
T0
M30
